# Generated by Django 4.1.7 on 2023-04-19 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000, verbose_name='First name')),
                ('last_name', models.CharField(max_length=1000, verbose_name='Last name')),
                ('company', models.CharField(max_length=1000, verbose_name='Company')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000, verbose_name='First name')),
                ('last_name', models.CharField(max_length=1000, verbose_name='Last name')),
                ('position', models.CharField(max_length=1000, verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('total_amount', models.IntegerField(verbose_name='Total amount')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=1000, verbose_name='Task name')),
                ('notes', models.CharField(max_length=1000, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('clients', models.ManyToManyField(to='project_mgmt_app.client')),
                ('employees', models.ManyToManyField(to='project_mgmt_app.employee')),
                ('invoices', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_mgmt_app.invoice')),
                ('tasks', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_mgmt_app.task')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
