# Generated by Django 4.1.7 on 2023-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgmt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='invoices',
            field=models.ManyToManyField(to='project_mgmt_app.invoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(to='project_mgmt_app.task'),
        ),
    ]
