# Generated by Django 4.2 on 2023-04-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgmt_app', '0003_remove_project_invoices_remove_project_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task', to='project_mgmt_app.project'),
        ),
    ]
