# Generated by Django 4.2 on 2023-04-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgmt_app', '0005_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='invoice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_mgmt_app.invoice'),
        ),
    ]
