# Generated by Django 4.2 on 2023-04-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgmt_app', '0006_remove_invoice_project_project_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_mgmt_app.project'),
        ),
    ]
